---
- name: Add Radius Setup
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Configure Radius Client
      community.network.routeros_command:
        commands:
          - /radius add address=35.227.71.209 secret=testing123 service=hotspot